# Generated by Django 6.0.7 on 2026-07-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='accounts.accounts')),
            ],
        ),
    ]
