# Generated by Django 6.0.7 on 2026-07-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_supervisorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='supervisors/default.png', null=True, upload_to='supervisors/'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='research_interests',
            field=models.CharField(blank=True, help_text='Comma-separated interests (e.g. AI, ML)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='status',
            field=models.CharField(choices=[('Accepting Students', 'Accepting Students'), ('Full', 'Full')], default='Accepting Students', max_length=50),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil', 'Civil'), ('Business', 'Business')], default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
