# Generated by Django 6.0.7 on 2026-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_supervisorprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
