# Generated by Django 6.0.7 on 2026-07-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_supervisorprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
