# Generated by Django 6.0.7 on 2026-07-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_studentprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
