# Generated by Django 6.0.7 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_supervisorprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='intake',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]