# Generated by Django 6.0.7 on 2026-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('authors', models.CharField(max_length=255)),
                ('supervisor_name', models.CharField(max_length=150)),
                ('domain', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='thesis_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
