# Generated by Django 6.0.7 on 2026-07-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisProposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proposed_title', models.CharField(max_length=255)),
                ('proposed_abstract', models.TextField()),
                ('similarity_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_proposals', to='accounts.accounts')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='accounts.accounts')),
            ],
        ),
    ]
