# Generated by Django 6.0.7 on 2026-08-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesisproposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='thesisproposal',
            name='similarity_score',
        ),
        migrations.AddField(
            model_name='thesisproposal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
        migrations.AddField(
            model_name='thesisproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='thesisproposal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
