# Generated by Django 6.1 on 2026-09-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_researchtopic_thesisproposal_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtopic',
            name='available_seats',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
