# Generated by Django 6.0.7 on 2026-07-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperEmbedding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sbert_embedding', models.JSONField(blank=True, null=True)),
                ('umap_x_coord', models.FloatField(blank=True, null=True)),
                ('umap_y_coord', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='research_library.thesispaper')),
            ],
        ),
    ]
