# Generated by Django 6.0.7 on 2026-07-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_groups', to='accounts.accounts')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_group', to='proposals.thesisproposal')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='milestone_submissions/')),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='progress_tracker.thesisgroup')),
            ],
        ),
    ]
