# Generated by Django 6.1 on 2026-09-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0002_milestone_status_milestone_submission_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Revision Required', 'Revision Required')], default='Pending', max_length=20),
        ),
    ]
